version: "3"
volumes:
  uploads:
    external: false
  database:
    external: false
networks:
  services: {}
services:
  api-service:
    image: enigmacamp/izmi/swipeschat-api
    restart: always
    ports:
      - 3939:3939
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://10.10.11.9:3306/db_percobaan?useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: swipes3cr3t
    volumes:
      - uploads:/uploads
    networks:
      - services
